import { BadDataCase, ChecklistRun } from "@/types";

export const sampleCases: BadDataCase[] = [
  {
    case_id: "BD-20260601-0001",
    created_date: "2026-06-01",
    rm_name: "RM Demo A",
    product: "KPR",
    cif: "900000000001",
    customer_name: "Nasabah Dummy 01",
    phone_number: "080000000001",
    issue_category: "CIF lama",
    source_system: "Kantor Pusat",
    process_stage: "Pengecekan awal",
    issue_description:
      "Data CIF dummy yang terinject masih mengarah ke CIF lama pada simulasi sumber pusat.",
    business_impact: "SLA prakarsa terhambat",
    priority: "High",
    status: "In Progress",
    assigned_pic: "PIC Operasional Demo",
    target_resolution_date: "2026-06-03",
    closed_date: null,
    action_taken: "RM melakukan pencocokan data dummy dan menyiapkan catatan eskalasi.",
    escalation_required: false,
    escalation_date: null,
    escalation_target: null,
    evidence_note: "Screenshot dummy tidak dilampirkan pada MVP.",
    created_by: "RM"
  },
  {
    case_id: "BD-20260602-0002",
    created_date: "2026-06-02",
    rm_name: "RM Demo B",
    product: "Briguna",
    cif: "900000000002",
    customer_name: "Nasabah Dummy 02",
    phone_number: "628000000002",
    issue_category: "Nomor HP format 62",
    source_system: "PIS",
    process_stage: "Pre-screening",
    issue_description:
      "Nomor HP dummy dari PIS masih menggunakan prefix 62 sehingga perlu dinormalisasi ke prefix 0.",
    business_impact: "Input ulang oleh RM",
    priority: "Medium",
    status: "Open",
    assigned_pic: "RM Demo B",
    target_resolution_date: "2026-06-07",
    closed_date: null,
    action_taken: "Belum ada tindakan lanjutan selain verifikasi awal.",
    escalation_required: false,
    escalation_date: null,
    escalation_target: null,
    evidence_note: "Catatan simulasi format nomor HP.",
    created_by: "RM"
  },
  {
    case_id: "BD-20260602-0003",
    created_date: "2026-06-02",
    rm_name: "RM Demo C",
    product: "Briguna",
    cif: "900000000003",
    customer_name: "Nasabah Dummy 03",
    phone_number: "080000000003",
    issue_category: "Nomor HP Data Leads tidak sesuai",
    source_system: "Data Leads",
    process_stage: "Pengkinian data",
    issue_description:
      "Nomor HP dummy pada Data Leads tidak sesuai dengan nomor aktual hasil konfirmasi simulasi.",
    business_impact: "Nasabah menunggu lebih lama",
    priority: "High",
    status: "Escalated",
    assigned_pic: "OPX Demo",
    target_resolution_date: "2026-06-04",
    closed_date: null,
    action_taken: "Sudah dibuat catatan eskalasi dummy.",
    escalation_required: true,
    escalation_date: "2026-06-03",
    escalation_target: "OPX",
    evidence_note: "Log Data Leads dummy dicatat secara tekstual.",
    created_by: "Admin"
  },
  {
    case_id: "BD-20260603-0004",
    created_date: "2026-06-03",
    rm_name: "RM Demo A",
    product: "KPR",
    cif: "900000000004",
    customer_name: "Nasabah Dummy 04",
    phone_number: "080000000004",
    issue_category: "Data revert saat submit/prakarsa",
    source_system: "BRISpot",
    process_stage: "Submit prakarsa",
    issue_description:
      "Data dummy yang sudah diperbarui kembali ke nilai sebelumnya ketika proses submit prakarsa.",
    business_impact: "Pengkinian manual berulang",
    priority: "Critical",
    status: "Waiting Feedback",
    assigned_pic: "PO Demo",
    target_resolution_date: "2026-06-04",
    closed_date: null,
    action_taken: "Cabang menunggu feedback atas simulasi kendala revert.",
    escalation_required: true,
    escalation_date: "2026-06-04",
    escalation_target: "PO",
    evidence_note: "Catatan kronologi dummy tersedia.",
    created_by: "Admin"
  },
  {
    case_id: "BD-20260604-0005",
    created_date: "2026-06-04",
    rm_name: "RM Demo D",
    product: "Briguna",
    cif: "900000000005",
    customer_name: "Nasabah Dummy 05",
    phone_number: "080000000005",
    issue_category: "Data tidak tersimpan",
    source_system: "Input RM",
    process_stage: "Pengkinian data",
    issue_description:
      "Update data dummy oleh RM tidak terlihat tersimpan konsisten setelah refresh halaman simulasi.",
    business_impact: "Input ulang oleh RM",
    priority: "Medium",
    status: "Closed",
    assigned_pic: "PIC Operasional Demo",
    target_resolution_date: "2026-06-09",
    closed_date: "2026-06-05",
    action_taken: "Data dummy diperbarui ulang dan status ditutup untuk simulasi.",
    escalation_required: false,
    escalation_date: null,
    escalation_target: null,
    evidence_note: "Tidak ada lampiran pada MVP.",
    created_by: "RM"
  },
  {
    case_id: "BD-20260605-0006",
    created_date: "2026-06-05",
    rm_name: "RM Demo E",
    product: "KPR",
    cif: "900000000006",
    customer_name: "Nasabah Dummy 06",
    phone_number: "080000000006",
    issue_category: "Tidak ada audit log",
    source_system: "BRISpot",
    process_stage: "Eskalasi",
    issue_description:
      "RM tidak memiliki akses mudah ke audit log per CIF dummy untuk memastikan perubahan terakhir.",
    business_impact: "Risiko data tidak valid",
    priority: "High",
    status: "Waiting Feedback",
    assigned_pic: "OPX Demo",
    target_resolution_date: "2026-06-07",
    closed_date: null,
    action_taken: "Eskalasi dummy dikirim dan menunggu feedback OPX/PO.",
    escalation_required: true,
    escalation_date: "2026-06-05",
    escalation_target: "OPX",
    evidence_note: "Kronologi dummy sudah disiapkan.",
    created_by: "Admin"
  },
  {
    case_id: "BD-20260606-0007",
    created_date: "2026-06-06",
    rm_name: "RM Demo B",
    product: "Briguna",
    cif: "900000000007",
    customer_name: "Nasabah Dummy 07",
    phone_number: "080000000007",
    issue_category: "Sinkronisasi PIS/Data Lakes belum optimal",
    source_system: "Data Lakes",
    process_stage: "Pre-screening",
    issue_description:
      "Data dummy dari PIS dan Data Lakes belum seragam saat dicek pada alur pre-screening.",
    business_impact: "SLA prakarsa terhambat",
    priority: "Low",
    status: "Open",
    assigned_pic: "Unit Data Demo",
    target_resolution_date: "2026-06-13",
    closed_date: null,
    action_taken: "RM mencatat perbedaan sumber data dummy.",
    escalation_required: false,
    escalation_date: null,
    escalation_target: null,
    evidence_note: "Catatan perbandingan sumber data dummy.",
    created_by: "RM"
  }
];

export const sampleChecklistRuns: ChecklistRun[] = [
  {
    run_date: "2026-06-06",
    product: "Briguna",
    rm_name: "RM Demo B",
    cif: "900000000007",
    phone_number: "628000000007",
    normalized_phone: "080000000007",
    cif_checked: true,
    cif_matches_latest: true,
    phone_exists: true,
    phone_format_valid: false,
    email_checked: true,
    job_business_checked: true,
    payroll_checked: true,
    supporting_docs_checked: true,
    slik_checked: true,
    brispot_matches_latest: false,
    no_data_mismatch: false,
    notes: "Checklist dummy menemukan format nomor HP dan mismatch BRISpot.",
    result_status: "Perlu Pengkinian",
    created_case_id: "BD-20260606-0007"
  }
];
