insert into bad_data_cases (
  case_id,
  created_date,
  rm_name,
  product,
  cif,
  customer_name,
  phone_number,
  issue_category,
  source_system,
  process_stage,
  issue_description,
  business_impact,
  priority,
  status,
  assigned_pic,
  target_resolution_date,
  closed_date,
  action_taken,
  escalation_required,
  escalation_date,
  escalation_target,
  evidence_note,
  created_by
) values
(
  'BD-20260601-0001',
  '2026-06-01',
  'RM Demo A',
  'KPR',
  '900000000001',
  'Nasabah Dummy 01',
  '080000000001',
  'CIF lama',
  'Kantor Pusat',
  'Pengecekan awal',
  'Data CIF dummy yang terinject masih mengarah ke CIF lama pada simulasi sumber pusat.',
  'SLA prakarsa terhambat',
  'High',
  'In Progress',
  'PIC Operasional Demo',
  '2026-06-03',
  null,
  'RM melakukan pencocokan data dummy dan menyiapkan catatan eskalasi.',
  false,
  null,
  null,
  'Screenshot dummy tidak dilampirkan pada MVP.',
  'RM'
),
(
  'BD-20260602-0002',
  '2026-06-02',
  'RM Demo B',
  'Briguna',
  '900000000002',
  'Nasabah Dummy 02',
  '628000000002',
  'Nomor HP format 62',
  'PIS',
  'Pre-screening',
  'Nomor HP dummy dari PIS masih menggunakan prefix 62 sehingga perlu dinormalisasi ke prefix 0.',
  'Input ulang oleh RM',
  'Medium',
  'Open',
  'RM Demo B',
  '2026-06-07',
  null,
  'Belum ada tindakan lanjutan selain verifikasi awal.',
  false,
  null,
  null,
  'Catatan simulasi format nomor HP.',
  'RM'
),
(
  'BD-20260602-0003',
  '2026-06-02',
  'RM Demo C',
  'Briguna',
  '900000000003',
  'Nasabah Dummy 03',
  '080000000003',
  'Nomor HP Data Leads tidak sesuai',
  'Data Leads',
  'Pengkinian data',
  'Nomor HP dummy pada Data Leads tidak sesuai dengan nomor aktual hasil konfirmasi simulasi.',
  'Nasabah menunggu lebih lama',
  'High',
  'Escalated',
  'OPX Demo',
  '2026-06-04',
  null,
  'Sudah dibuat catatan eskalasi dummy.',
  true,
  '2026-06-03',
  'OPX',
  'Log Data Leads dummy dicatat secara tekstual.',
  'Admin'
),
(
  'BD-20260603-0004',
  '2026-06-03',
  'RM Demo A',
  'KPR',
  '900000000004',
  'Nasabah Dummy 04',
  '080000000004',
  'Data revert saat submit/prakarsa',
  'BRISpot',
  'Submit prakarsa',
  'Data dummy yang sudah diperbarui kembali ke nilai sebelumnya ketika proses submit prakarsa.',
  'Pengkinian manual berulang',
  'Critical',
  'Waiting Feedback',
  'PO Demo',
  '2026-06-04',
  null,
  'Cabang menunggu feedback atas simulasi kendala revert.',
  true,
  '2026-06-04',
  'PO',
  'Catatan kronologi dummy tersedia.',
  'Admin'
),
(
  'BD-20260604-0005',
  '2026-06-04',
  'RM Demo D',
  'Briguna',
  '900000000005',
  'Nasabah Dummy 05',
  '080000000005',
  'Data tidak tersimpan',
  'Input RM',
  'Pengkinian data',
  'Update data dummy oleh RM tidak terlihat tersimpan konsisten setelah refresh halaman simulasi.',
  'Input ulang oleh RM',
  'Medium',
  'Closed',
  'PIC Operasional Demo',
  '2026-06-09',
  '2026-06-05',
  'Data dummy diperbarui ulang dan status ditutup untuk simulasi.',
  false,
  null,
  null,
  'Tidak ada lampiran pada MVP.',
  'RM'
),
(
  'BD-20260605-0006',
  '2026-06-05',
  'RM Demo E',
  'KPR',
  '900000000006',
  'Nasabah Dummy 06',
  '080000000006',
  'Tidak ada audit log',
  'BRISpot',
  'Eskalasi',
  'RM tidak memiliki akses mudah ke audit log per CIF dummy untuk memastikan perubahan terakhir.',
  'Risiko data tidak valid',
  'High',
  'Waiting Feedback',
  'OPX Demo',
  '2026-06-07',
  null,
  'Eskalasi dummy dikirim dan menunggu feedback OPX/PO.',
  true,
  '2026-06-05',
  'OPX',
  'Kronologi dummy sudah disiapkan.',
  'Admin'
),
(
  'BD-20260606-0007',
  '2026-06-06',
  'RM Demo B',
  'Briguna',
  '900000000007',
  'Nasabah Dummy 07',
  '080000000007',
  'Sinkronisasi PIS/Data Lakes belum optimal',
  'Data Lakes',
  'Pre-screening',
  'Data dummy dari PIS dan Data Lakes belum seragam saat dicek pada alur pre-screening.',
  'SLA prakarsa terhambat',
  'Low',
  'Open',
  'Unit Data Demo',
  '2026-06-13',
  null,
  'RM mencatat perbedaan sumber data dummy.',
  false,
  null,
  null,
  'Catatan perbandingan sumber data dummy.',
  'RM'
)
on conflict (case_id) do update set
  created_date = excluded.created_date,
  rm_name = excluded.rm_name,
  product = excluded.product,
  cif = excluded.cif,
  customer_name = excluded.customer_name,
  phone_number = excluded.phone_number,
  issue_category = excluded.issue_category,
  source_system = excluded.source_system,
  process_stage = excluded.process_stage,
  issue_description = excluded.issue_description,
  business_impact = excluded.business_impact,
  priority = excluded.priority,
  status = excluded.status,
  assigned_pic = excluded.assigned_pic,
  target_resolution_date = excluded.target_resolution_date,
  closed_date = excluded.closed_date,
  action_taken = excluded.action_taken,
  escalation_required = excluded.escalation_required,
  escalation_date = excluded.escalation_date,
  escalation_target = excluded.escalation_target,
  evidence_note = excluded.evidence_note,
  created_by = excluded.created_by;
